version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    env_file: ./docker.env
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - MYSQL_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build: ./v2
    environment:
      - REACT_APP_BACKEND_URI=http://localhost
    ports:
      - "3000:3000"
    depends_on:
      - backend