import mongoose from "mongoose";
var Schema = mongoose.Schema;
const entryShema = new Schema({
  title: String,
  description: String,
  createdAt: { type: Date, default: Date.now() },
  updatedAt: { type: Date, default: Date.now() },
  address: String,
  city: String,
  postal: String,
  price: Number,
  priceCleaning: Number,
  rooms: Number,
  image: String,
  userId: mongoose.Schema.Types.ObjectId,
  amenities: {
    familyFriendly: Boolean,
    luggageDropoff: Boolean,
    petsAllowed: Boolean,
    smokingAllowed: Boolean,
    aircon: Boolean,
    balcony: Boolean,
    bath: Boolean,
    beach: Boolean,
    beachEssentials: Boolean,
    breakfast: Boolean,
    carbonMonoxideDetector: Boolean,
    crib: Boolean,
    dryer: Boolean,
    elevator: Boolean,
    essentials: Boolean,
    ethernetConnection: Boolean,
    fireExtinguisher: Boolean,
    fireplace: Boolean,
    firstAidKit: Boolean,
    freeParking: Boolean,
    garden: Boolean,
    gym: Boolean,
    hairDryer: Boolean,
    hangers: Boolean,
    heating: Boolean,
    highChair: Boolean,
    iron: Boolean,
    jacuzzi: Boolean,
    kitchen: Boolean,
    pool: Boolean,
    safe: Boolean,
    securityCamera: Boolean,
    selfCheckIn: Boolean,
    seperateEntrance: Boolean,
    shampoo: Boolean,
    ski: Boolean,
    smokeDetector: Boolean,
    tv: Boolean,
    washer: Boolean,
    wifi: Boolean,
    workspace: Boolean,
    wheelchairAccessible: Boolean,
  },
});

const Entry = mongoose.models.Entry || mongoose.model("Entry", entryShema);
export default Entry;